name: CI
on: [push, pull_request, workflow_dispatch]
env:
  ProjectName: ShadowsocksR

jobs:

  build:
    name: Build
    runs-on: windows-latest
    env:
      SyncfusionLicenseKey: ${{ secrets.SyncfusionLicenseKey }}
      NET_TFM: net7.0-windows
      Configuration: Release

    steps:
    - name: Checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: Setup NuGet Private Sources
      shell: pwsh
      run: dotnet nuget add source https://nuget.pkg.github.com/HMBSbige/index.json -n GitHub-HMBSbige -u HMBSbige -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Build .NET App
      shell: pwsh
      run: .\build.ps1 app

    - name: Build x64
      shell: pwsh
      run: .\build.ps1 x64

    - name: Build x86
      shell: pwsh
      run: .\build.ps1 x86

    - name: Upload .NET App
      continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ProjectName }}
        path: shadowsocks-csharp\bin\${{ env.Configuration }}\${{ env.NET_TFM }}\publish\

    - name: Upload x64
      continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ProjectName }}-Win64
        path: shadowsocks-csharp\bin\${{ env.Configuration }}\${{ env.NET_TFM }}\win-x64\publish\

    - name: Upload x86
      continue-on-error: true
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ProjectName }}-Win32
        path: shadowsocks-csharp\bin\${{ env.Configuration }}\${{ env.NET_TFM }}\win-x86\publish\
